[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ballsdex-merchant"
version = "0.0.0"

description = "A travelling merchant to sell balls."
license = "MIT"
authors = [
    { name = "Haymooed" },
]
readme = "README.md"

dependencies = [

]
